### ISSUE TITLE
Array values not getting passed into nocache block

### ISSUE THREAD

**Issue by architchandra** [ttempleton/craft-nocache#24] opened 2021-06-05 10:28 UTC
### Description
In some circumstances, array values are not getting passed into the `nocache` block (scalar values seem to be working fine), and array-related Twig filters (like `|merge`) inside the `nocache` block are complaining about the input not being an array.

### Steps to reproduce
I'm not able to reproduce this consistently right now, but the following steps should be a starting point. Will add updates as soon as I can. 
1. Create a `nocache` block that uses array values from outside it.
2. Apply the merge filter on the array value inside the nocache block (can even be something like `set arr = arr|merge('[]')`).

### Additional information
- No-Cache version: `2.0.7`
- Craft CMS version: `3.5.19.1`
- PHP version: `7.4.19`

**Comment by ttempleton** [comment] 2021-06-13 07:00
Your example of `set arr = arr|merge('[]')` would cause an error since `'[]'` is a string, but I'm guessing that was a typo.

When passing in an array to the `nocache` block and merging it with another array, I haven't been able to reproduce this error so far, so any updates you can provide to narrow down what causes it will definitely be appreciated.

**Comment by ttempleton** [comment] 2021-07-04 12:34
Closing this issue for now, but if you have any updates that could help me reproduce it, please let me know and I'll reopen.

**Closed by ttempleton** 2021-07-04 12:34 UTC
