### ISSUE TITLE
The nocache plugin is not working with CKEditor Longform

### ISSUE THREAD

**Issue by thomascoppein** [ttempleton/craft-nocache#31] opened 2024-09-16 07:45 UTC
### Description
Since CKEditor 4.1.0 there has been some changes. 
The issue seems to be related to how Craft handles rendering CKEditor content when saving an entry. When the entry is saved, the partial templates for nested CKEditor entries are rendered, which results in an exception. This exception appears to be caused by the use of the {% nocache %} tag, which typically only works during site requests.

It seems that this exception occurs because the template rendering happens outside of a site request. One possible cause is that the Nocache plugin only registers its Twig extension for site requests.

### Steps to reproduce
1. Create entry type with nocache tags
2. Add entry type to Ckeditor
3. Try to save

![image](https://github.com/user-attachments/assets/72f14433-0885-4a96-abf6-1b7ab33e22b1)

### Additional information
- No-Cache version: 3.0.2
- Craft CMS version: 5.4.2
- CKEditor version: 4.2.0
- PHP version: 8.2

**Comment by thomascoppein** [comment] 2024-09-16 07:47
I've made a [pull request](https://github.com/ttempleton/craft-nocache/pull/32) which resolves this problem.

**Comment by ttempleton** [comment] 2024-09-16 09:25
It works for me:

<img width="542" alt="Screenshot 2024-09-16 at 19 16 24" src="https://github.com/user-attachments/assets/1dbc09d1-9075-482a-9aa2-db672599f763">
<img width="598" alt="Screenshot 2024-09-16 at 19 16 37" src="https://github.com/user-attachments/assets/2a9622db-edc9-486a-a97f-9dfa60a1558f">
<img width="311" alt="Screenshot 2024-09-16 at 19 16 05" src="https://github.com/user-attachments/assets/d07a069a-7734-46d6-aaa8-3a6cb410a741">

Let me know if I'm misunderstanding something about how to reproduce the error; otherwise, if you're able to reproduce it on a new Craft install, please provide detailed steps to reproduce.

**Comment by thomascoppein** [comment] 2024-09-16 14:03
Hi @ttempleton , thanks for the quick response. Which version of CKEditor do you use?
I've made a simple test entry type and updated to the latest version of no-cache, Craft CMS and CKEditor. 
But I still get this error:
![image](https://github.com/user-attachments/assets/75f9e1e5-6a9d-40cb-a1c3-1dbde72b8a80)

This is my partial code:
```twig
Test
{% nocache %}{{ entry.title }}{% endnocache %}
```

- ckeditor: 4.2.0,
- craftcms: 5.4.4,
- nocache: 3.0.3

**Comment by ttempleton** [comment] 2024-09-20 10:27
I've also got 4.2.0.

Does the error still occur if you disable all other plugins? If so, try re-enabling them one by one, and see which one causes the error. I can't find anything in the CKEditor plugin documentation about rendering entry templates on save (although admittedly I'm not that familiar with CKEditor and could've missed it) so I'm wondering if a third plugin is interfering somehow.

**Comment by brandonkelly** [comment] 2024-09-23 17:39
@ttempleton Per craftcms/ckeditor#248, the issue is occurring when the CKEditor field is rendered as part of an entry type’s Title Format, which happens on entry save (CP request).

I agree that #32 should be merged as a temporary solution.

I’ve also just [added](https://github.com/craftcms/cms/commit/5ffd69f62591c5e4047a0e5425f26e23f4dec2fe) new `View::registerCpTwigExtension()` and `registerSiteTwigExtension()` methods for Craft 4.13 and 5.5, which you could start calling instead of `registerTwigExtension()` once those are out. That would be a far safer way to limit the extension to site templates, knowing that sometimes site templates can be rendered from the control panel (or vise-versa).

**Comment by ttempleton** [comment] 2024-09-24 09:16
Thanks @brandonkelly. I can now reproduce the error and am happy to merge @thomascoppein's pull request to resolve it.

**Closed by ttempleton** 2024-09-24 09:16 UTC
