### ISSUE TITLE
{% js %} not outputting when inside nocache

### ISSUE THREAD

**Issue by amityweb** [ttempleton/craft-nocache#23] opened 2021-03-04 13:35 UTC
I have an include file which contains JS via {% js %} tags

This include file is inside {% nocache %} tags

The JS is not being output on the page. It was all fine before using nocache

Can it be linked to this?

**Comment by ttempleton** [comment] 2021-04-02 09:09
While looking into this, I found that `{% js %}` and `{% script %}` tags inside `{% cache %}` would output the `<script>` tag on the first page load and not afterwards, so I've reported that at craftcms/cms#7758.  I think that's related to this issue, given the similarity of the behaviour (only difference being that `{% js %}` / `{% script %}` inside `{% nocache %}` *never* works), but will leave this issue open in case they're not related.

**Comment by ttempleton** [comment] 2021-04-03 01:32
The aforementioned Craft issue was closed with the advice "You should avoid calling those tags within `{% cache %}` tags."  Following on from that, given that the point of `{% nocache %}` is to be used inside `{% cache %}`, my advice here is going to be "You should avoid calling those tags within `{% nocache %}` tags."

Unfortunately, since I'm pretty sure this issue is being caused by Craft's behaviour, it doesn't look like I can do any more about this, so I have no choice other than to close the issue.  I'll be happy to reopen it if the two issues turn out to be unrelated, though.

**Closed by ttempleton** 2021-04-03 01:32 UTC
